export const classes = {
  db_spring_2024: [
    // "Abdulla, Azhar Y.",
    // "Alilaikannan, Dharana",
    // "Araki, Joji",
    // "Asmat, Omer",
    // "Bajpai, Arssh",
    // "Batacan, Nina Jade C.",
    // "Bermudez, John Mark B.",
    // "Blum, Zachary T.",
    // "Borer, Alec D.",
    // "Brook, Joel",
    // "Cameron, Cole A.",
    // "Chen, Kaylee",
    // "Chen, Kylan",
    // "Chen, Xinyu",
    // "Dsouza, Ethan I.",
    // "Dziugelis, Vilius",
    // "Emily chooi, Kai",
    // "Feng, Yuki",
    // "Gandhi, Marvin N.",
    // "Gannamani, Arnav",
    // "Gupta, Aarushi",
    // "Hall, Anna",
    // "Hill, Zachary D.",
    // "Huang, Eric J.",
    // "Jahangir, Zaydaan",
    // "Johnson, Aaron N.",
    // "Kalae, Youssef",
    // "Kang, Aileen",
    // "Karthik, Abhishiek",
    // "Kawano, Sena",
    // "Khan, Mia M.",
    // "Koo, Grace M.",
    // "Kumar, Arav",
    // "Lane, Lily L.",
    // "Langis, Christos T.",
    // "Legault, William D.",
    // "Li, Xinzichen",
    // "Liu, Fengkai",
    // "Liu, Justin",
    // "Lota, Tyler T.",
    // "Luo, Yucheng",
    // "McCue, Daniel R.",
    // "Medici, Jacob A.",
    // "Mehta, Rohan",
    // "Nadarasa, Niraj N.",
    // "Narang, Jairaj S.",
    // "Padmanabhuni, Saisri Deepa",
    // "Pan, William L.",
    // "Patel, Gia",
    // "Patwal, Aditya",
    // "Paulino Ozuna, Joshua",
    // "Pemmaraju, Praphul",
    // "Pokhrel, Shishir",
    // "Porat, Isaac",
    // "Prates, Vitor F.",
    // "Pujara, Abhishek",
    // "Riser, William S.",
    // "Sahoo, Anish",
    // "Sharma, Aarushi",
    // "Shi, Bohan",
    // "Singh, Vaibhav",
    // "Sinha, Jahanavi",
    // "Sklyarevskiy, Daniel",
    // "Srinivasan, SaiPraharshitha",
    // "Sukhwani, Vansh",
    // "Verghese, Nikhil C.",
    // "Vijay, Darshini",
    // "West, Demetrios A.",
    // "Xu, Fiora",
    // "Yeow, Isabel",
    // "Zhang, Jerry",
    // "Zocco, Jake A.",
    "Abdulla, Azhar Y.",
    "Araki, Joji",
    "Bajpai, Arssh",
    "Belbisi, Raneem H.",
    "Blum, Zachary T.",
    "Brook, Joel",
    "Cameron, Cole A.",
    "Chen, Kaylee",
    "Chen, Kylan",
    "Chitra, Sai Vishnu -.",
    "Dsouza, Ethan I.",
    "Emily chooi, Kai",
    "Hill, Zachary D.",
    // "Hong, Leechan", // Feb 3
    "Johnson, Aaron N.",
    "Kalae, Youssef",
    "Kawano, Sena",
    "Khan, Mia M.",
    "Koo, Grace M.",
    "Lane, Lily L.",
    "Legault, William D.",
    "Liu, Fengkai",
    "Liu, Justin",
    "Nadarasa, Niraj N.",
    "Pan, William L.",
    "Pemmaraju, Praphul",
    "Pokhrel, Shishir",
    "Porat, Isaac",
    "Riser, William S.",
    "Sahoo, Anish",
    "Shi, Bohan",
    "Sklyarevskiy, Daniel",
    "Thomas, Lloyd A.",
    "Verghese, Nikhil C.",
    "West, Demetrios A.",
    "Xu, Fiora",
    "Zocco, Jake A.",
  ],
  pdp_spring_2024: [
    // "Chatterjee, Agnibha",
    // "Chen, Wentao",
    // "Li, Zhiang",
    // "Lin, Kaiyue",
    // "Ling, Zhi",
    // "Liu, Siyuan",
    // "M, Tarun",
    // "Malla, Saugat",
    // "Qiao, Yuqing",
    // "Sowrirajan Balaji, Pranav Raj",
    // "Vora, Prem Bhavesh",
    // "Wadhwani, Diya D.",
    // "Wang, Qichen",
    // "Wang, Zhi",
    // "Xia, Jing",
    // "Yu, Dexu",
    // "Zhao, Yang",

    // jan 18th
    "Chatterjee, Agnibha",
    "Chen, Wentao",
    "Li, Zhiang",
    "Lin, Kaiyue",
    "Ling, Zhi",
    "Liu, Siyuan",
    "M, Tarun",
    "Malla, Saugat",
    "Qiao, Yuqing",
    "Sowrirajan Balaji, Pranav Raj",
    "Vora, Prem Bhavesh",
    "Wadhwani, Diya D.",
    "Wang, Qichen",
    "Wang, Zhi",
    "Xia, Jing",
    "Yu, Dexu",
    "Zhao, Yang"
  ],

  // webdev_fall_2023: [
  //   "Cui, Yushi",
  //   "Diaz Rodas, Vicki A.",
  //   "Gadiraju, Srija",
  //   "Htoo, Hla",
  //   "Hu, Huiqin",
  //   "Li, Dongze",
  //   "Liu, Xiaolin",
  //   "Saremi, Ali",
  //   "Tao, Peng",
  //   "Tilahun, Senay Argaw",
  //   // "Ye, Tong",
  //   "Chen, Lixing",
  //   // "Chen, Xinyao",
  //   "Hu, Yuqi",
  //   "Huang, Chuanzhao",
  //   "Huang, Yue",
  //   "Jotwani, Gaurang",
  //   // "Liao, Sujuan",
  //   "Liu, Junyi",
  //   "Liu, Tianjing",
  //   "Nie, Yunke",
  //   "Shah, Jishva M.",
  //   "Sun, Congkai",
  //   "Wu, Yue",
  //   "Xu, Zhehao",
  //   "Zhang, Naiyi",
  //   "Zhang, Xiangyue",
  //   "Zhang, Yahui",
  //   "Zhang, Zhiqian",
  //   "Zhou, Fan",
  //   "Puerta, Eduardo",
  //   "Huang, Xinyuan",
  //   "Gong, Zexi",
  //   "Qi, Wenxin"
  // ],
  // db_fall_2023: [
  //   "Liu, Huazhou",
  //   "Mesia, Mihir Himmatbhai",
  //   "Sorho, Founyakon S.",
  //   "Zhang, Haozhe",
  //   "Zhang, Yuze",
  //   "Zhong, Yao",
  //   // "Bei, Chenjie",
  //   "Cai, Lihan",
  //   "Chen, Zexi",
  //   "Hu, Xinyi",
  //   "Hu, Zhengyan",
  //   "Koradiya, Twinkalbahen J.",
  //   "Ngo, Triet M.",
  //   "Santoshi, Harshika",
  //   // "Shambanna, Shreevidhya",
  //   "Wang, YuWei",
  //   "Yang, Wenhanfu",
  //   "Yi, Liheng",
  //   "Zhang, Hejia",
  //   // "Zhang, Shuxin",
  //   "Mei, Yufei",
  //   "Shao, Yuting"
  // ],
  lottery_tests: ["John", "Mafe"],
};
